### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by kinghuin** [sa-j/MachineComprehension#1]
Hi, I am a student interested in this project. But there appears to be a lack of documentation,such as 

- _squad.pkl
- dictionary_squad.pkl    
- unchanged_W_squad.pkl 
- oov_in_train_W_squad.pkl  ,etc.

How can I get these files? :)

**Comment by sa-j** [comment]
Hi Kinghuin,

If the issue still exists, here is the solution: You don't need the .pkl-files listed above, they are created during the preprocessing of the raw SQuAD data. Have a look at **squad_dataset_exploration.py**.

Best, Saj
